name: "Security scan"

on:
  workflow_dispatch: # Allows you to trigger this scan manually from the Actions tab

jobs:
  secrets-scan:
    name: Secrets Scan
    uses: ./.github/workflows/secrets-scan.yml

  codeql:
    needs: secrets-scan
    name: CodeQL
    uses: ./.github/workflows/CodeQL-Security.yml
    with:
      languages: "javascript"
    permissions:
      contents: read          # read repository code
      security-events: write  # upload alerts to the Security tab
      actions: read     